// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bili "oh-my-helper-go/apps/app/api/internal/handler/bili"
	push "oh-my-helper-go/apps/app/api/internal/handler/push"
	task "oh-my-helper-go/apps/app/api/internal/handler/task"
	"oh-my-helper-go/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bili/qrCode",
				Handler: bili.BiliQrCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bili/login",
				Handler: bili.BiliQrCodeLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bili/user",
				Handler: bili.BiliUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bili/users",
				Handler: bili.BiliUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tasks/bili",
				Handler: task.BiliTaskConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tasks/bili",
				Handler: task.BiliTaskConfigAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tasks/bili/:cid",
				Handler: task.BiliTaskConfigEditHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/push",
				Handler: push.PushConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/push",
				Handler: push.PushConfigAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/push/:cid",
				Handler: push.PushConfigEditHandler(serverCtx),
			},
		},
	)
}
