// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: bilibili.proto

package bilibili

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QrCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QrCodeRequest) Reset() {
	*x = QrCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QrCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCodeRequest) ProtoMessage() {}

func (x *QrCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCodeRequest.ProtoReflect.Descriptor instead.
func (*QrCodeRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{0}
}

type QrCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QrCodeUrl string `protobuf:"bytes,1,opt,name=QrCodeUrl,proto3" json:"QrCodeUrl,omitempty"`
	QrCodeImg string `protobuf:"bytes,2,opt,name=QrCodeImg,proto3" json:"QrCodeImg,omitempty"`
	QrCodeKey string `protobuf:"bytes,3,opt,name=QrCodeKey,proto3" json:"QrCodeKey,omitempty"`
}

func (x *QrCodeResponse) Reset() {
	*x = QrCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QrCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCodeResponse) ProtoMessage() {}

func (x *QrCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCodeResponse.ProtoReflect.Descriptor instead.
func (*QrCodeResponse) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{1}
}

func (x *QrCodeResponse) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

func (x *QrCodeResponse) GetQrCodeImg() string {
	if x != nil {
		return x.QrCodeImg
	}
	return ""
}

func (x *QrCodeResponse) GetQrCodeKey() string {
	if x != nil {
		return x.QrCodeKey
	}
	return ""
}

type BiliLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QrCodeKey string `protobuf:"bytes,1,opt,name=QrCodeKey,proto3" json:"QrCodeKey,omitempty"`
}

func (x *BiliLoginRequest) Reset() {
	*x = BiliLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiliLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiliLoginRequest) ProtoMessage() {}

func (x *BiliLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiliLoginRequest.ProtoReflect.Descriptor instead.
func (*BiliLoginRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{2}
}

func (x *BiliLoginRequest) GetQrCodeKey() string {
	if x != nil {
		return x.QrCodeKey
	}
	return ""
}

type BiliLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       uint32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Dedeuserid string `protobuf:"bytes,2,opt,name=Dedeuserid,proto3" json:"Dedeuserid,omitempty"`
	Sessdata   string `protobuf:"bytes,3,opt,name=Sessdata,proto3" json:"Sessdata,omitempty"`
	BiliJct    string `protobuf:"bytes,4,opt,name=BiliJct,proto3" json:"BiliJct,omitempty"`
}

func (x *BiliLoginResponse) Reset() {
	*x = BiliLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiliLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiliLoginResponse) ProtoMessage() {}

func (x *BiliLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiliLoginResponse.ProtoReflect.Descriptor instead.
func (*BiliLoginResponse) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{3}
}

func (x *BiliLoginResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BiliLoginResponse) GetDedeuserid() string {
	if x != nil {
		return x.Dedeuserid
	}
	return ""
}

func (x *BiliLoginResponse) GetSessdata() string {
	if x != nil {
		return x.Sessdata
	}
	return ""
}

func (x *BiliLoginResponse) GetBiliJct() string {
	if x != nil {
		return x.BiliJct
	}
	return ""
}

type BiliUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dedeuserid string `protobuf:"bytes,1,opt,name=Dedeuserid,proto3" json:"Dedeuserid,omitempty"`
	Sessdata   string `protobuf:"bytes,2,opt,name=Sessdata,proto3" json:"Sessdata,omitempty"`
	BiliJct    string `protobuf:"bytes,3,opt,name=BiliJct,proto3" json:"BiliJct,omitempty"`
}

func (x *BiliUserRequest) Reset() {
	*x = BiliUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiliUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiliUserRequest) ProtoMessage() {}

func (x *BiliUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiliUserRequest.ProtoReflect.Descriptor instead.
func (*BiliUserRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{4}
}

func (x *BiliUserRequest) GetDedeuserid() string {
	if x != nil {
		return x.Dedeuserid
	}
	return ""
}

func (x *BiliUserRequest) GetSessdata() string {
	if x != nil {
		return x.Sessdata
	}
	return ""
}

func (x *BiliUserRequest) GetBiliJct() string {
	if x != nil {
		return x.BiliJct
	}
	return ""
}

type BiliUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Dedeuserid    string  `protobuf:"bytes,2,opt,name=Dedeuserid,proto3" json:"Dedeuserid,omitempty"`
	Username      string  `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	Coins         float64 `protobuf:"fixed64,4,opt,name=Coins,proto3" json:"Coins,omitempty"`
	Level         int64   `protobuf:"varint,5,opt,name=Level,proto3" json:"Level,omitempty"`
	CurrentExp    int64   `protobuf:"varint,6,opt,name=CurrentExp,proto3" json:"CurrentExp,omitempty"`
	NextExp       int64   `protobuf:"varint,7,opt,name=NextExp,proto3" json:"NextExp,omitempty"`
	UpgradeDays   int64   `protobuf:"varint,8,opt,name=UpgradeDays,proto3" json:"UpgradeDays,omitempty"`
	Medals        string  `protobuf:"bytes,9,opt,name=Medals,proto3" json:"Medals,omitempty"`
	VipStatus     int64   `protobuf:"varint,10,opt,name=VipStatus,proto3" json:"VipStatus,omitempty"`
	VipType       int64   `protobuf:"varint,11,opt,name=VipType,proto3" json:"VipType,omitempty"`
	VipLabelTheme string  `protobuf:"bytes,12,opt,name=VipLabelTheme,proto3" json:"VipLabelTheme,omitempty"`
	Sign          string  `protobuf:"bytes,13,opt,name=Sign,proto3" json:"Sign,omitempty"`
	IsLogin       bool    `protobuf:"varint,14,opt,name=IsLogin,proto3" json:"IsLogin,omitempty"`
	LastRunTime   int64   `protobuf:"varint,15,opt,name=LastRunTime,proto3" json:"LastRunTime,omitempty"`
	CreateTime    int64   `protobuf:"varint,16,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
}

func (x *BiliUserResponse) Reset() {
	*x = BiliUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiliUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiliUserResponse) ProtoMessage() {}

func (x *BiliUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiliUserResponse.ProtoReflect.Descriptor instead.
func (*BiliUserResponse) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{5}
}

func (x *BiliUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BiliUserResponse) GetDedeuserid() string {
	if x != nil {
		return x.Dedeuserid
	}
	return ""
}

func (x *BiliUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BiliUserResponse) GetCoins() float64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *BiliUserResponse) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BiliUserResponse) GetCurrentExp() int64 {
	if x != nil {
		return x.CurrentExp
	}
	return 0
}

func (x *BiliUserResponse) GetNextExp() int64 {
	if x != nil {
		return x.NextExp
	}
	return 0
}

func (x *BiliUserResponse) GetUpgradeDays() int64 {
	if x != nil {
		return x.UpgradeDays
	}
	return 0
}

func (x *BiliUserResponse) GetMedals() string {
	if x != nil {
		return x.Medals
	}
	return ""
}

func (x *BiliUserResponse) GetVipStatus() int64 {
	if x != nil {
		return x.VipStatus
	}
	return 0
}

func (x *BiliUserResponse) GetVipType() int64 {
	if x != nil {
		return x.VipType
	}
	return 0
}

func (x *BiliUserResponse) GetVipLabelTheme() string {
	if x != nil {
		return x.VipLabelTheme
	}
	return ""
}

func (x *BiliUserResponse) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *BiliUserResponse) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *BiliUserResponse) GetLastRunTime() int64 {
	if x != nil {
		return x.LastRunTime
	}
	return 0
}

func (x *BiliUserResponse) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type BiliUserListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *BiliUserListRequest) Reset() {
	*x = BiliUserListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiliUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiliUserListRequest) ProtoMessage() {}

func (x *BiliUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiliUserListRequest.ProtoReflect.Descriptor instead.
func (*BiliUserListRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{6}
}

func (x *BiliUserListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BiliUserListRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BiliUserListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total     int64               `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	BiliUsers []*BiliUserResponse `protobuf:"bytes,2,rep,name=biliUsers,proto3" json:"biliUsers,omitempty"`
}

func (x *BiliUserListResponse) Reset() {
	*x = BiliUserListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiliUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiliUserListResponse) ProtoMessage() {}

func (x *BiliUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiliUserListResponse.ProtoReflect.Descriptor instead.
func (*BiliUserListResponse) Descriptor() ([]byte, []int) {
	return file_bilibili_proto_rawDescGZIP(), []int{7}
}

func (x *BiliUserListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BiliUserListResponse) GetBiliUsers() []*BiliUserResponse {
	if x != nil {
		return x.BiliUsers
	}
	return nil
}

var File_bilibili_proto protoreflect.FileDescriptor

var file_bilibili_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x22, 0x0f, 0x0a, 0x0d, 0x51, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x0e, 0x51,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x51, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x51, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x51,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x51, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6d, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x51, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x51, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x30, 0x0a, 0x10, 0x42, 0x69, 0x6c, 0x69, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x51,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x51, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x7d, 0x0a, 0x11, 0x42, 0x69, 0x6c,
	0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x64, 0x65, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x64, 0x65, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x73, 0x73, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x73, 0x73, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x42, 0x69, 0x6c, 0x69, 0x4a, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x42, 0x69, 0x6c, 0x69, 0x4a, 0x63, 0x74, 0x22, 0x67, 0x0a, 0x0f, 0x42, 0x69, 0x6c, 0x69,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x44,
	0x65, 0x64, 0x65, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x44, 0x65, 0x64, 0x65, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x65, 0x73, 0x73, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53,
	0x65, 0x73, 0x73, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x69, 0x6c, 0x69, 0x4a,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x69, 0x6c, 0x69, 0x4a, 0x63,
	0x74, 0x22, 0xcc, 0x03, 0x0a, 0x10, 0x42, 0x69, 0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x64, 0x65, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x64, 0x65,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x4e, 0x65, 0x78, 0x74, 0x45, 0x78, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x4e, 0x65, 0x78, 0x74, 0x45, 0x78, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x44, 0x61, 0x79, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x44, 0x61, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65,
	0x64, 0x61, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x56, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x56, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x56, 0x69,
	0x70, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x56, 0x69, 0x70, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x54, 0x68, 0x65, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x53, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x3d, 0x0a, 0x13, 0x42, 0x69, 0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x66, 0x0a, 0x14, 0x42, 0x69, 0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x38, 0x0a,
	0x09, 0x62, 0x69, 0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x42, 0x69, 0x6c, 0x69,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x62, 0x69,
	0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x73, 0x32, 0x98, 0x02, 0x0a, 0x08, 0x42, 0x69, 0x6c, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x12, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x51, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x51, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x51, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x05, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x42, 0x69,
	0x6c, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x42, 0x69, 0x6c, 0x69, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x42,
	0x69, 0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x42, 0x69, 0x6c, 0x69, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x05, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x42,
	0x69, 0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x42, 0x69,
	0x6c, 0x69, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_proto_rawDescOnce sync.Once
	file_bilibili_proto_rawDescData = file_bilibili_proto_rawDesc
)

func file_bilibili_proto_rawDescGZIP() []byte {
	file_bilibili_proto_rawDescOnce.Do(func() {
		file_bilibili_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_proto_rawDescData)
	})
	return file_bilibili_proto_rawDescData
}

var file_bilibili_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bilibili_proto_goTypes = []interface{}{
	(*QrCodeRequest)(nil),        // 0: bilibili.QrCodeRequest
	(*QrCodeResponse)(nil),       // 1: bilibili.QrCodeResponse
	(*BiliLoginRequest)(nil),     // 2: bilibili.BiliLoginRequest
	(*BiliLoginResponse)(nil),    // 3: bilibili.BiliLoginResponse
	(*BiliUserRequest)(nil),      // 4: bilibili.BiliUserRequest
	(*BiliUserResponse)(nil),     // 5: bilibili.BiliUserResponse
	(*BiliUserListRequest)(nil),  // 6: bilibili.BiliUserListRequest
	(*BiliUserListResponse)(nil), // 7: bilibili.BiliUserListResponse
}
var file_bilibili_proto_depIdxs = []int32{
	5, // 0: bilibili.BiliUserListResponse.biliUsers:type_name -> bilibili.BiliUserResponse
	0, // 1: bilibili.Bilibili.GetLoginQrCode:input_type -> bilibili.QrCodeRequest
	2, // 2: bilibili.Bilibili.Login:input_type -> bilibili.BiliLoginRequest
	4, // 3: bilibili.Bilibili.User:input_type -> bilibili.BiliUserRequest
	6, // 4: bilibili.Bilibili.Users:input_type -> bilibili.BiliUserListRequest
	1, // 5: bilibili.Bilibili.GetLoginQrCode:output_type -> bilibili.QrCodeResponse
	3, // 6: bilibili.Bilibili.Login:output_type -> bilibili.BiliLoginResponse
	5, // 7: bilibili.Bilibili.User:output_type -> bilibili.BiliUserResponse
	7, // 8: bilibili.Bilibili.Users:output_type -> bilibili.BiliUserListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bilibili_proto_init() }
func file_bilibili_proto_init() {
	if File_bilibili_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QrCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QrCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiliLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiliLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiliUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiliUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiliUserListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiliUserListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bilibili_proto_goTypes,
		DependencyIndexes: file_bilibili_proto_depIdxs,
		MessageInfos:      file_bilibili_proto_msgTypes,
	}.Build()
	File_bilibili_proto = out.File
	file_bilibili_proto_rawDesc = nil
	file_bilibili_proto_goTypes = nil
	file_bilibili_proto_depIdxs = nil
}
