// Code generated by goctl. DO NOT EDIT.
// Source: bilibili.proto

package server

import (
	"context"

	"oh-my-helper-go/apps/bilibili/rpc/bilibili"
	"oh-my-helper-go/apps/bilibili/rpc/internal/logic"
	"oh-my-helper-go/apps/bilibili/rpc/internal/svc"
)

type BilibiliServer struct {
	svcCtx *svc.ServiceContext
	bilibili.UnimplementedBilibiliServer
}

func NewBilibiliServer(svcCtx *svc.ServiceContext) *BilibiliServer {
	return &BilibiliServer{
		svcCtx: svcCtx,
	}
}

func (s *BilibiliServer) GetLoginQrCode(ctx context.Context, in *bilibili.QrCodeRequest) (*bilibili.QrCodeResponse, error) {
	l := logic.NewGetLoginQrCodeLogic(ctx, s.svcCtx)
	return l.GetLoginQrCode(in)
}

func (s *BilibiliServer) Login(ctx context.Context, in *bilibili.BiliLoginRequest) (*bilibili.BiliLoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *BilibiliServer) User(ctx context.Context, in *bilibili.BiliUserRequest) (*bilibili.BiliUserResponse, error) {
	l := logic.NewUserLogic(ctx, s.svcCtx)
	return l.User(in)
}

func (s *BilibiliServer) Users(ctx context.Context, in *bilibili.BiliUserListRequest) (*bilibili.BiliUserListResponse, error) {
	l := logic.NewUsersLogic(ctx, s.svcCtx)
	return l.Users(in)
}
