// Code generated by goctl. DO NOT EDIT.
// Source: pushconfig.proto

package server

import (
	"context"

	"oh-my-helper-go/apps/pushconfig/internal/logic"
	"oh-my-helper-go/apps/pushconfig/internal/svc"
	"oh-my-helper-go/apps/pushconfig/pushconfig"
)

type PushConfigServer struct {
	svcCtx *svc.ServiceContext
	pushconfig.UnimplementedPushConfigServer
}

func NewPushConfigServer(svcCtx *svc.ServiceContext) *PushConfigServer {
	return &PushConfigServer{
		svcCtx: svcCtx,
	}
}

func (s *PushConfigServer) Ping(ctx context.Context, in *pushconfig.Request) (*pushconfig.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *PushConfigServer) GetPushConfig(ctx context.Context, in *pushconfig.PushConfigRequest) (*pushconfig.PushConfigResponse, error) {
	l := logic.NewGetPushConfigLogic(ctx, s.svcCtx)
	return l.GetPushConfig(in)
}

func (s *PushConfigServer) AddPushConfig(ctx context.Context, in *pushconfig.PushConfigAddRequest) (*pushconfig.PushConfigResponse, error) {
	l := logic.NewAddPushConfigLogic(ctx, s.svcCtx)
	return l.AddPushConfig(in)
}

func (s *PushConfigServer) EditPushConfig(ctx context.Context, in *pushconfig.PushConfigEditRequest) (*pushconfig.PushConfigResponse, error) {
	l := logic.NewEditPushConfigLogic(ctx, s.svcCtx)
	return l.EditPushConfig(in)
}
