// Code generated by goctl. DO NOT EDIT.
// Source: bilibili.proto

package bilibiliclient

import (
	"context"

	"oh-my-helper-go/apps/bilibili/rpc/bilibili"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BiliLoginRequest     = bilibili.BiliLoginRequest
	BiliLoginResponse    = bilibili.BiliLoginResponse
	BiliUserListRequest  = bilibili.BiliUserListRequest
	BiliUserListResponse = bilibili.BiliUserListResponse
	BiliUserRequest      = bilibili.BiliUserRequest
	BiliUserResponse     = bilibili.BiliUserResponse
	QrCodeRequest        = bilibili.QrCodeRequest
	QrCodeResponse       = bilibili.QrCodeResponse

	Bilibili interface {
		GetLoginQrCode(ctx context.Context, in *QrCodeRequest, opts ...grpc.CallOption) (*QrCodeResponse, error)
		Login(ctx context.Context, in *BiliLoginRequest, opts ...grpc.CallOption) (*BiliLoginResponse, error)
		User(ctx context.Context, in *BiliUserRequest, opts ...grpc.CallOption) (*BiliUserResponse, error)
		Users(ctx context.Context, in *BiliUserListRequest, opts ...grpc.CallOption) (*BiliUserListResponse, error)
	}

	defaultBilibili struct {
		cli zrpc.Client
	}
)

func NewBilibili(cli zrpc.Client) Bilibili {
	return &defaultBilibili{
		cli: cli,
	}
}

func (m *defaultBilibili) GetLoginQrCode(ctx context.Context, in *QrCodeRequest, opts ...grpc.CallOption) (*QrCodeResponse, error) {
	client := bilibili.NewBilibiliClient(m.cli.Conn())
	return client.GetLoginQrCode(ctx, in, opts...)
}

func (m *defaultBilibili) Login(ctx context.Context, in *BiliLoginRequest, opts ...grpc.CallOption) (*BiliLoginResponse, error) {
	client := bilibili.NewBilibiliClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultBilibili) User(ctx context.Context, in *BiliUserRequest, opts ...grpc.CallOption) (*BiliUserResponse, error) {
	client := bilibili.NewBilibiliClient(m.cli.Conn())
	return client.User(ctx, in, opts...)
}

func (m *defaultBilibili) Users(ctx context.Context, in *BiliUserListRequest, opts ...grpc.CallOption) (*BiliUserListResponse, error) {
	client := bilibili.NewBilibiliClient(m.cli.Conn())
	return client.Users(ctx, in, opts...)
}
