// Code generated by goctl. DO NOT EDIT.
// Source: taskconfig.proto

package taskconfigclient

import (
	"context"

	"oh-my-helper-go/apps/taskconfig/taskconfig"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BiliConfigAddRequest  = taskconfig.BiliConfigAddRequest
	BiliConfigEditRequest = taskconfig.BiliConfigEditRequest
	BiliConfigRequest     = taskconfig.BiliConfigRequest
	BiliConfigResponse    = taskconfig.BiliConfigResponse
	Request               = taskconfig.Request
	Response              = taskconfig.Response

	TaskConfig interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		GetBiliConfig(ctx context.Context, in *BiliConfigRequest, opts ...grpc.CallOption) (*BiliConfigResponse, error)
		EditBiliConfig(ctx context.Context, in *BiliConfigEditRequest, opts ...grpc.CallOption) (*BiliConfigResponse, error)
		AddBiliConfig(ctx context.Context, in *BiliConfigAddRequest, opts ...grpc.CallOption) (*BiliConfigResponse, error)
	}

	defaultTaskConfig struct {
		cli zrpc.Client
	}
)

func NewTaskConfig(cli zrpc.Client) TaskConfig {
	return &defaultTaskConfig{
		cli: cli,
	}
}

func (m *defaultTaskConfig) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := taskconfig.NewTaskConfigClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultTaskConfig) GetBiliConfig(ctx context.Context, in *BiliConfigRequest, opts ...grpc.CallOption) (*BiliConfigResponse, error) {
	client := taskconfig.NewTaskConfigClient(m.cli.Conn())
	return client.GetBiliConfig(ctx, in, opts...)
}

func (m *defaultTaskConfig) EditBiliConfig(ctx context.Context, in *BiliConfigEditRequest, opts ...grpc.CallOption) (*BiliConfigResponse, error) {
	client := taskconfig.NewTaskConfigClient(m.cli.Conn())
	return client.EditBiliConfig(ctx, in, opts...)
}

func (m *defaultTaskConfig) AddBiliConfig(ctx context.Context, in *BiliConfigAddRequest, opts ...grpc.CallOption) (*BiliConfigResponse, error) {
	client := taskconfig.NewTaskConfigClient(m.cli.Conn())
	return client.AddBiliConfig(ctx, in, opts...)
}
